#!/bin/sh

set -e

case "${1}" in
	configure)
	    update-alternatives --install /usr/share/backgrounds/default_background.jpg \
		    deepin-default-background /usr/share/backgrounds/deepin/desktop.jpg 50
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		;;
esac
exit 0
