#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
    remove|deconfigure|failed-upgrade)
	update-alternatives --remove deepin-default-background \
	    /usr/share/wallpapers/deepin/default_background.jpg
	;;
esac

